.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-list - List all saved snapshots


.SH SYNOPSIS
\fBhostfile list [flags]\fP


.SH DESCRIPTION
List all saved snapshots


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
