.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-enable - Enable a disabled entry


.SH SYNOPSIS
\fBhostfile enable  [flags]\fP


.SH DESCRIPTION
Enable a disabled entry


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for enable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
