.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-load - Load a saved snapshot into the managed block


.SH SYNOPSIS
\fBhostfile load  [flags]\fP


.SH DESCRIPTION
Load a saved snapshot into the managed block


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for load


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
