.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-init - Initialize hostfile management for the current hosts file


.SH SYNOPSIS
\fBhostfile init [flags]\fP


.SH DESCRIPTION
Backup the current hosts file as "origin", then reorganize all entries
into the managed block format and overwrite the hosts file.

.PP
If a managed block already exists, entries outside the block are merged in.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for init


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
