.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-apply - Replace the managed block with content from a file


.SH SYNOPSIS
\fBhostfile apply  [flags]\fP


.SH DESCRIPTION
Replace the managed block with content from a file


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for apply


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
