.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-search - Search the managed block for an IP or domain


.SH SYNOPSIS
\fBhostfile search  [flags]\fP


.SH DESCRIPTION
Search the managed block for an IP or domain


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for search


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
