.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-merge - Merge content from a file into the managed block


.SH SYNOPSIS
\fBhostfile merge  [flags]\fP


.SH DESCRIPTION
Merge content from a file into the managed block


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for merge


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
