.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-remove - Remove an IP or domain from the managed block


.SH SYNOPSIS
\fBhostfile remove  [flags]\fP


.SH DESCRIPTION
Remove an IP or domain from the managed block


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
