.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-add - Add domains to an IP address


.SH SYNOPSIS
\fBhostfile add   [domain2...] [flags]\fP


.SH DESCRIPTION
Add domains to an IP address


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for add


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
