.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile - Cross-platform hosts file manager


.SH SYNOPSIS
\fBhostfile [flags]\fP


.SH DESCRIPTION
A CLI tool for managing your hosts file with ease.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for hostfile

.PP
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile-add(1)\fP, \fBhostfile-apply(1)\fP, \fBhostfile-clean(1)\fP, \fBhostfile-delete(1)\fP, \fBhostfile-disable(1)\fP, \fBhostfile-enable(1)\fP, \fBhostfile-init(1)\fP, \fBhostfile-list(1)\fP, \fBhostfile-load(1)\fP, \fBhostfile-merge(1)\fP, \fBhostfile-remove(1)\fP, \fBhostfile-save(1)\fP, \fBhostfile-search(1)\fP, \fBhostfile-show(1)\fP, \fBhostfile-version(1)\fP
