.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-show - Show entries in the managed block, or show a saved snapshot


.SH SYNOPSIS
\fBhostfile show [name] [flags]\fP


.SH DESCRIPTION
Show entries in the managed block, or show a saved snapshot


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for show


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
