.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-disable - Disable an entry without removing it


.SH SYNOPSIS
\fBhostfile disable  [flags]\fP


.SH DESCRIPTION
Disable an entry without removing it


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
