.nh
.TH "HOSTFILE" "1" "Jan 0001" "hostfile" "User Commands"

.SH NAME
hostfile-clean - Clear all entries from the managed block


.SH SYNOPSIS
\fBhostfile clean [flags]\fP


.SH DESCRIPTION
Clear all entries from the managed block


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for clean


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--hosts-file\fP="/etc/hosts"
	path to hosts file


.SH SEE ALSO
\fBhostfile(1)\fP
